"use client";

import { useEffect, useState } from "react";
type Tab="command"|"opportunities"|"websites"|"leads"|"revenue"|"intelligence"|"activity";
type Mission={id:string;objective:string;status:string;progress:number;currentStage:string;updatedAt:string};
type Opportunity={id:string;businessName:string;category:string;location:string;score:number;signals:string[];status:string;contactEmail?:string;deployedWebsiteUrl?:string};
type Asset={id:string;opportunityId:string;type:string;title:string;content:string;status:string;deploymentUrl?:string;createdAt:string};
type Lead={id:string;opportunityId:string;name:string;email?:string;phone?:string;message?:string;status:string};
type Revenue={id:string;opportunityId?:string;type:string;amount:number;currency:string;note:string;createdAt:string};
type Deal={id:string;opportunityId:string;leadId?:string;value:number;currency:string;status:string};
type Response={id:string;leadId:string;content:string;channel:string;status:string;kind?:string;createdAt:string};
const tabs:[Tab,string][]=[["command","Command"],["opportunities","Opportunities"],["websites","Websites"],["leads","Leads"],["revenue","Revenue"],["intelligence","Intelligence"],["activity","Activity"]];

export default function Home(){
 const [tab,setTab]=useState<Tab>("command"),[mission,setMission]=useState<Mission|null>(null),[missions,setMissions]=useState<Mission[]>([]),[opportunities,setOpportunities]=useState<Opportunity[]>([]),[assets,setAssets]=useState<Asset[]>([]),[leads,setLeads]=useState<Lead[]>([]),[revenue,setRevenue]=useState<Revenue[]>([]),[deals,setDeals]=useState<Deal[]>([]),[responses,setResponses]=useState<Response[]>([]);
 const [learning,setLearning]=useState<any>(null),[economics,setEconomics]=useState<any>(null),[economicLearning,setEconomicLearning]=useState<any>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function refresh(){const r=await Promise.all(["/api/missions","/api/opportunities","/api/assets","/api/leads","/api/revenue","/api/deals","/api/execution","/api/revenue-learning","/api/economics","/api/economic-learning"].map(x=>fetch(x,{cache:"no-store"})));if(!r.every(x=>x.ok))throw Error("Workspace refresh failed");const [m,o,a,l,v,d,rr,rl,ec,el]=await Promise.all(r.map(x=>x.json()));setMissions(m);setMission(m[0]||null);setOpportunities(o);setAssets(a);setLeads(l);setRevenue(v);setDeals(d);setResponses(rr);setLearning(rl);setEconomics(ec);setEconomicLearning(el)}
 async function launch(){setBusy("mission");setError("");try{const r=await fetch("/api/missions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({objective:"Find and pursue the highest-value next revenue opportunity."})});const m=await r.json();if(!r.ok)throw Error(m.error);setMission(m);setNotice("Mission queued. Discovery is running.");fetch("/api/missions/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({missionId:m.id})}).catch(()=>{});for(let i=0;i<20;i++){await new Promise(x=>setTimeout(x,1000));await refresh().catch(()=>{});const ms=await fetch("/api/missions",{cache:"no-store"}).then(x=>x.json()).catch(()=>[]);const cur=ms.find((x:Mission)=>x.id===m.id);if(cur)setMission(cur);if(cur?.status==="completed"||cur?.status==="failed")break}}catch(e){setError(e instanceof Error?e.message:"Mission failed")}finally{setBusy("")}}
 async function post(url:string,body:any,key:string,msg:string){setBusy(key);setError("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Action failed");setNotice(msg);await refresh()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}}
 async function build(o:string,a:"website"|"offer"|"outreach"){await post("/api/operator",{opportunityId:o,action:a},o+a,a==="website"?"Website built.":a==="offer"?"Offer built.":"Outreach draft built.")}
 async function audit(o:string){setBusy(o+"audit");try{const r=await fetch("/api/revenue-audits?opportunityId="+encodeURIComponent(o));const d=await r.json();if(!r.ok)throw Error(d.error);setNotice("Revenue audit complete.");setAuditData(x=>({...x,[o]:d}))}catch(e){setError(e instanceof Error?e.message:"Audit failed")}finally{setBusy("")}}
 const [auditData,setAuditData]=useState<Record<string,any>>({});
 async function publish(a:Asset){setBusy(a.id);try{let r=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assetId:a.id,action:"publish"})});let d=await r.json();if(!r.ok)throw Error(d.error);r=await fetch("/api/deployments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assetId:a.id})});d=await r.json();if(!r.ok)throw Error(d.error);setNotice("Website published.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Publish failed")}finally{setBusy("")}}
 async function respond(id:string){await post("/api/execution",{action:"respond",leadId:id},id+"r","AI response drafted. Review before sending.")}
 async function approveResponse(id:string){await post("/api/execution",{action:"approve_response",responseId:id},id+"a","Response approved. Ready to send.")}
 async function sendResponse(id:string){await post("/api/execution",{action:"send_response",responseId:id},id+"s","Response sent. Follow-up scheduled.")}
 async function meeting(l:Lead){await post("/api/execution",{action:"appointment",leadId:l.id,startsAt:new Date(Date.now()+86400000).toISOString()},l.id+"m","Appointment recorded.")}
 async function deal(l:Lead){const v=prompt("Deal value (USD)","2000");if(v)await post("/api/execution",{action:"deal",leadId:l.id,opportunityId:l.opportunityId,value:Number(v)},l.id+"d","Deal created.")}
 async function won(d:Deal){await post("/api/execution",{action:"close_deal",dealId:d.id,status:"won"},d.id+"w","Deal closed-won and attributed.")}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const websites=assets.filter(a=>a.type==="website"),wonRevenue=revenue.filter(x=>x.type==="won"||x.type==="payment").reduce((n,x)=>n+x.amount,0),pipeline=revenue.filter(x=>x.type==="pipeline").reduce((n,x)=>n+x.amount,0);
 return <main className="shell"><header className="nav"><div className="brand"><span className="brand-mark">✦</span>NORTHSTAR</div><div className="status"><span/>AUTONOMOUS CORE ONLINE</div><button className="ghost" onClick={launch} disabled={!!busy}>{busy==="mission"?"RUNNING…":"RUN MISSION →"}</button></header>
 <nav className="product-nav">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {error&&<div className="global-error">{error}</div>}{notice&&<div className="global-notice">{notice}</div>}
 {tab==="command"&&<section className="workspace"><span className="eyebrow">REVENUE EXECUTION ENGINE</span><h1>From opportunity to <em>revenue.</em></h1><p className="hero-copy">Discover → audit → build → capture → respond → meet → close → attribute.</p><div className="command-grid"><div className="command-card"><small>MISSION</small><strong>{mission?.status?.toUpperCase()||"READY"}</strong><span>{mission?.currentStage||"Awaiting execution"}</span><div className="progress"><i style={{width:(mission?.progress||0)+"%"}}/></div><button className="primary" onClick={launch}>START MISSION</button></div><div className="command-card"><small>OPPORTUNITIES</small><strong>{opportunities.length}</strong><span>ranked business signals · economic allocation active</span><button className="secondary" onClick={()=>setTab("opportunities")}>OPEN →</button></div><div className="command-card"><small>ECONOMIC PRIORITY</small><strong>{economics?.ranked?.length||0}</strong><span>${(economics?.allocated||0).toFixed(2)} of ${(economics?.budget||0).toFixed(2)} execution budget allocated</span><button className="secondary" onClick={()=>setTab("opportunities")}>OPEN →</button></div><div className="command-card"><small>ATTRIBUTED REVENUE</small><strong>{"$"}{wonRevenue.toLocaleString()}</strong><span>{"$"}{pipeline.toLocaleString()} pipeline</span><button className="secondary" onClick={()=>setTab("revenue")}>OPEN →</button></div></div><div className="execution-loop">{["DISCOVER","AUDIT","BUILD","RESPOND","CLOSE"].map((x,i)=><div key={x}><b>0{i+1} {x}</b><span>{["Find real businesses.","Quantify the revenue gap.","Create the required assets.","Handle inbound demand.","Prove the money generated."][i]}</span></div>)}</div></section>}
 {tab==="opportunities"&&<section className="workspace"><div className="section-head"><div><span className="eyebrow">OPPORTUNITY INTELLIGENCE</span><h2>Businesses Northstar can pursue</h2></div><button className="secondary" onClick={launch}>RUN NEW SCAN</button></div><div className="opportunity-grid">{opportunities.map(o=><article className="opportunity" key={o.id}><div className="score">{o.score}</div><div className="opportunity-main"><strong>{o.businessName}</strong><span>{o.category} · {o.location}</span><div className="signal-row">{(o.signals||[]).slice(0,3).map(s=><span key={s}>{s}</span>)}</div>{economics?.ranked?.filter((x:any)=>x.opportunityId===o.id).map((x:any)=><div className="audit-result" key={x.opportunityId}><b>{x.recommendation.toUpperCase()}</b><span>EV ${x.expectedValue.toFixed(0)} · ${x.expectedCashVelocity.toFixed(0)}/day · {Math.round(x.winProbability*100)}% win estimate</span></div>)}<div className="action-row"><button className="audit-button" onClick={()=>audit(o.id)}>{busy===o.id+"audit"?"ANALYZING…":"REVENUE AUDIT"}</button><button className="audit-button" onClick={()=>build(o.id,"website")}>BUILD WEBSITE</button><button className="audit-button" onClick={()=>build(o.id,"offer")}>BUILD OFFER</button>{o.contactEmail&&<button className="audit-button" onClick={()=>build(o.id,"outreach")}>DRAFT OUTREACH</button>}</div>{auditData[o.id]&&<div className="audit-result"><b>{auditData[o.id].confidence}% confidence</b><span>{"$"}{auditData[o.id].modeledAnnualRevenue.low.toLocaleString()}–{"$"}{auditData[o.id].modeledAnnualRevenue.high.toLocaleString()} modeled annual upside</span></div>}</div><small className="opp-status">{o.status.toUpperCase()}</small></article>)}{!opportunities.length&&<div className="empty">Run a mission to discover businesses.</div>}</div></section>}
 {tab==="websites"&&<section className="workspace"><div className="section-head"><div><span className="eyebrow">WEBSITE FACTORY</span><h2>Assets and deployments</h2></div></div><div className="asset-grid">{websites.map(a=><article className="asset-card" key={a.id}><small>{opportunities.find(o=>o.id===a.opportunityId)?.businessName||"Opportunity"}</small><strong>{a.title}</strong><span>{a.status.toUpperCase()}</span>{a.deploymentUrl?<a className="live-link" href={a.deploymentUrl} target="_blank">OPEN LIVE SITE ↗</a>:<button className="publish" onClick={()=>publish(a)}>{busy===a.id?"PUBLISHING…":"APPROVE & PUBLISH"}</button>}</article>)}{!websites.length&&<div className="empty">No website assets. Build one from Opportunities.</div>}</div></section>}
 {tab==="leads"&&<section className="workspace"><div className="section-head"><div><span className="eyebrow">REVENUE EXECUTION</span><h2>Lead → response → meeting → deal</h2></div><span>{leads.length} LEADS</span></div><div className="lead-list">{leads.map(l=><article className="lead-card" key={l.id}><div><strong>{l.name}</strong><span>{l.email||l.phone||"No contact"}</span><small>{opportunities.find(o=>o.id===l.opportunityId)?.businessName||"Opportunity"}</small></div><b>{l.status.toUpperCase()}</b><p>{l.message||"No message supplied."}</p><div className="action-row"><button className="audit-button" onClick={()=>respond(l.id)}>AI RESPONSE</button><button className="audit-button" onClick={()=>meeting(l)}>RECORD MEETING</button><button className="audit-button" onClick={()=>deal(l)}>CREATE DEAL</button>{deals.filter(d=>d.leadId===l.id).map(d=><button key={d.id} className="publish" onClick={()=>won(d)} disabled={d.status==="won"}>{d.status==="won"?"WON":"CLOSE WON"}</button>)}</div>{responses.filter(r=>r.leadId===l.id).slice(0,3).map(r=><div className="response-card" key={r.id}><small>{(r.kind||"initial").replace("_"," ").toUpperCase()} · {r.status.toUpperCase()}</small><p>{r.content}</p><div className="action-row">{r.status==="draft"&&<button className="audit-button" onClick={()=>approveResponse(r.id)}>APPROVE</button>}{r.status==="approved"&&<button className="publish" onClick={()=>sendResponse(r.id)}>SEND EMAIL</button>}</div></div>)}</article>)}{!leads.length&&<div className="empty">No leads yet. Publish a website and submit its lead form.</div>}</div></section>}
 {tab==="revenue"&&<section className="workspace"><span className="eyebrow">ATTRIBUTION</span><h2>Revenue generated, not activity</h2><div className="metric-grid"><div><small>WON</small><strong>{"$"}{wonRevenue.toLocaleString()}</strong></div><div><small>PIPELINE</small><strong>{"$"}{pipeline.toLocaleString()}</strong></div><div><small>LEADS</small><strong>{leads.length}</strong></div><div><small>WON DEALS</small><strong>{deals.filter(d=>d.status==="won").length}</strong></div></div><div className="revenue-list">{revenue.map(r=><article key={r.id}><b>{r.type.toUpperCase()}</b><strong>{r.currency} {r.amount.toLocaleString()}</strong><span>{r.note}</span></article>)}</div></section>}
 {tab==="intelligence"&&<section className="workspace"><span className="eyebrow">REVENUE INTELLIGENCE LAB</span><h2>Teach Northstar what actually converts</h2><p className="hero-copy">Northstar now links strategy experiments to real outcomes, weights learning by revenue, and only promotes contextual winners after sufficient evidence.</p><div className="command-grid"><div className="command-card"><small>ATTRIBUTED REVENUE</small><strong>$ {(learning?.totalRevenue||0).toLocaleString()}</strong><span>{learning?.attributionCount||0} experiment outcomes linked to revenue</span></div><div className="command-card"><small>PLAYBOOKS</small><strong>{learning?.playbooks?.length||0}</strong><span>Contextual winners eligible for autonomous reuse</span></div><div className="command-card"><small>ECONOMIC EVIDENCE</small><strong>{economicLearning?.observations?.length||0}</strong><span>Observed outcomes recalibrating the economic model</span></div></div><div className="execution-loop">{(learning?.playbooks||[]).slice(0,6).map((p:any)=><div key={p.id}><b>{p.context.industry.toUpperCase()} · {p.context.channel.toUpperCase()}</b><span>{p.recommendedVariantName} · {Math.round(p.confidence*100)}% confidence · {Math.round(p.lift*100)}% revenue lift</span></div>)}</div><div className="command-grid"><div className="command-card"><small>ORANGE DATASET</small><strong>LIVE</strong><span>Real opportunities and outcomes</span><a className="primary" href="/api/intelligence/orange">DOWNLOAD CSV</a></div><div className="command-card"><small>MODEL WORKFLOW</small><strong>READY</strong><span>Rank and test outcome predictors</span><a className="secondary" href="/workflows/northstar-opportunity-intelligence.ows" target="_blank">OPEN WORKFLOW</a></div></div><div className="execution-loop"><div><b>01 ATTRIBUTE</b><span>Link experiments to real deals and revenue.</span></div><div><b>02 WEIGHT</b><span>Revenue matters more than raw activity.</span></div><div><b>03 PROVE</b><span>Require sufficient evidence before promotion.</span></div><div><b>04 EVOLVE</b><span>Feed validated playbooks into autonomous decisions.</span></div></div></section>}{tab==="activity"&&<section className="workspace"><span className="eyebrow">EXECUTION HISTORY</span><h2>What Northstar actually did</h2><div className="mission-list">{missions.map(m=><article key={m.id}><b>{m.status.toUpperCase()}</b><strong>{m.objective}</strong><span>{m.currentStage} · {m.progress}%</span><small>{new Date(m.updatedAt).toLocaleString()}</small></article>)}</div></section>}
 <footer><span>NORTHSTAR / REVENUE EXECUTION ENGINE</span><span>DISCOVER · BUILD · RESPOND · CLOSE · MEASURE</span></footer></main>
}